---
production: &default
  serverPort: 9898
  baseUrl: http://www.pips.com
  baseApi: /api/
  views:
    engine: .hbs
    extension: .hbs
    layout: main
  html:
    minify: true
    css:
      compress: true
      stylusPrecompile: true
  controllers:
    default: home
  languages:
    default: en
    list: [en, es, fr, pt, jp]

stage: &stage
  <<: *default
  baseUrl: http://stage.pips.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.pips.com

development:
  <<: *latest
  baseUrl: http://local.pipa.com
  html:
    minify: false
    stylusPrecompile: false
